---
- hosts: all
  become: true
  tasks:
    - name: install apache and php of Fedora
      ansible.builtin.dnf:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
        use_backend: dnf
      when: ansible_distribution == "Fedora"


    - name: install apache and php of Ubuntu
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      when: ansible_distribution != "Fedora"
