- name: install apache on web servers (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: install apache on web servers (fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    name: httpd
    use_backend: dnf
  when: ansible_distribution == "Fedora"

- name: launch Apache
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin nhattai@nguyen.net
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy html file for site
  tags: apache
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
